<font color=red size=10 >D01 Numpy 陣列的定義與屬性 Homework</font>

In [1]:
import numpy as np

In [2]:
# 生成一個等差數列，首數為0，尾數為20，公差為1的數列。
arr=np.arange(21)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# 呈上題，將以上數列取出偶數。
arr_2=arr[::2]
print(arr_2)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [4]:
# 呈1題，將數列取出3的倍數。
arr_3=arr[::3]
print(arr_3)

[ 0  3  6  9 12 15 18]


In [5]:
# [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
# print('list(a): ', list(a))
# print('tolist(): ', a.tolist())

# '''Answer
# list()只會將最外層的元素轉換成列表
# tolist()則會將多維的陣列架構轉換為多維的列表

# '''

In [6]:
# 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）
# a = np.random.randint(10, size=6) 
# b = np.random.randint(10, size=(3,4)) 
# c = np.random.randint(10, size=(2,3,2)) 

a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

for i in [a,b,c]:
    print(i.ndim,i.shape,i.size,i.dtype,i.itemsize,len(i),type(i),sep='\n',end='\n'*3)

# '''Answer
# 屬性ndim為陣列的維度數量
# 屬性shape為陣列內各個維度的大小
# 屬性size為陣列內元素的總數列，即屬性shape內元素的乘積
# 屬性dtype為陣列內元素的資料型態
# 屬性itemsize為陣列中每個元素佔用的空間,即陣列記憶體空間位元組的長度
# length為函式len所回傳的陣列的元素個數,只計算最外層的元素
# type為函式type所回傳的陣列的資料型態,即為類別numpy.ndarray

# '''

1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>




In [7]:
# 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

tolist_ = lambda arr: list(map(tolist_, arr)) if isinstance(arr, np.ndarray) else arr

for i in [a,b,c]:
    print(list(tolist_(i)))
    print(i.tolist())

[4, 9, 3, 0, 8, 2]
[4, 9, 3, 0, 8, 2]
[[7, 9, 3, 9], [7, 6, 1, 7], [7, 3, 2, 7]]
[[7, 9, 3, 9], [7, 6, 1, 7], [7, 3, 2, 7]]
[[[6, 1], [0, 3], [2, 3]], [[9, 7], [1, 6], [2, 5]]]
[[[6, 1], [0, 3], [2, 3]], [[9, 7], [1, 6], [2, 5]]]
