<font color=red size=10 >D02 Numpy 陣列的初始化Homework</font>

In [1]:
import numpy as np

In [2]:
# [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

# '''Answer
# np.zeros()可以依照傳入的引數來建立特定大小且全為0的陣列。
# np.empty()則是依照傳入的引數來建立特定大小且元素未初始化的陣列。

# '''

In [5]:
# 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
a = np.random.rand(2, 3)*100
a2=a.copy().round()

print(a)
print(a2)

[[ 1.70816679 36.96404508 22.0469942 ]
 [96.73941044 31.80666734 25.6560776 ]]
[[ 2. 37. 22.]
 [97. 32. 26.]]


In [15]:
# 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
m = 20
n = 40

from numpy.random import default_rng
integers = default_rng().integers(m, n, size=(2,3))
print(integers)

# 在不用「整數亂數方法」的限制下

a = np.random.rand(2, 3)
print((a * (n - m)).round() + m)


[[21 39 30]
 [32 26 22]]
[[34. 25. 37.]
 [36. 30. 23.]]
