<font color=red size=10 >D05 NumPy 陣列的邏輯運算 Homework</font>

In [1]:
import numpy as np

In [2]:
# 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
arr=np.array([i if i < 3 or i > 6 else -i for i in range(1,12)])
print(arr)

arr=np.array(range(1,12))
arr[2:6]=-arr[2:6]
print(arr)


[ 1  2 -3 -4 -5 -6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [3]:
# 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
a = np.random.rand(3, 6)

print(a)
print(len(a[a[:]>0.5]))

[[0.09762157 0.36140514 0.99793609 0.37623992 0.69895856 0.73519232]
 [0.8839689  0.11561868 0.75960718 0.75415494 0.05676925 0.19237139]
 [0.16052742 0.38616946 0.01213061 0.51305377 0.37343214 0.13130488]]
7
