<font color=red size=10 >D05 NumPy 陣列的邏輯運算 Homework</font>

In [1]:
import numpy as np

In [13]:
# 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
arr=np.array([i if i < 3 or i > 6 else -i for i in range(1,12)])
print(arr)

arr=np.array(range(1,12))
arr[2:6]=-arr[2:6]
print(arr)


[ 1  2 -3 -4 -5 -6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [20]:
# 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
a = np.random.rand(3, 6)

print(a[a[:]>0.5])

TypeError: 'int' object is not callable

In [23]:
# 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

A = np.ones((1,6))
B = np.ones((6,1))
print(A @ B)
print(A * B)

[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
